api_joinBandRequestAction:
    path:     /joinBandRequestAction/{bandId}/{musicianId}
    defaults: { _controller: "ZEBABundle:Api:joinBandRequest" }
api_joinBandAcceptAction:
    path:     /joinBandAcceptAction/{bandId}/{musicianId}
    defaults: { _controller: "ZEBABundle:Api:joinBandAccept" }
api_getMessagesAction:
    path:     /getMessagesAction/
    defaults: { _controller: "ZEBABundle:Api:getMessages" }
api_deleteMessagesAction:
    path:     /deleteMessagesAction/{msgIds}
    defaults: { _controller: "ZEBABundle:Api:deleteMessages" }
api_saveNewAddressAction:
    path:     /saveNewAddressAction/{associationId}/{associationType}/{address}
    defaults: { _controller: "ZEBABundle:Api:saveNewAddress" }
api_getAllImagesByAssociationId:
    path:     /getAllImagesByAssociationId/{associationId}
    defaults: { _controller: "ZEBABundle:Api:getAllImagesByAssociationId" }
api_deleteDocumentsAction:
    path:     /deleteDocumentsAction/{ids}/{associationId}
    defaults: { _controller: "ZEBABundle:Api:deleteDocuments" }