api_joinBandRequestAction:
    path:     /joinBandRequestAction/{bandId}/{musicianId}
    defaults: { _controller: "ZEBABundle:Api:joinBandRequest" }

api_getAllImagesByAssociationId:
    path:     /getAllImagesByAssociationId/{associationId}
    defaults: { _controller: "ZEBABundle:Api:getAllImagesByAssociationId" }