Country:
    type: entity
    table: country
    fields:
        countryCode:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
            column: country_code
            generator:
                strategy: IDENTITY
        countryName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: country_name
    lifecycleCallbacks: {  }
