EntityMedia:
    type: entity
    table: entity_media
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        mediaType:
            type: integer
            unsigned: false
            nullable: false
            column: media_type
    manyToOne:
        entity:
            targetEntity: Entity
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                entity_id:
                    referencedColumnName: id
            orphanRemoval: false
        media:
            targetEntity: Media
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                media_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
