EntityType:
    type: entity
    table: entity_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 32
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
