EntityLocation:
    type: entity
    table: entity_location
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        entityId:
            type: integer
            unsigned: false
            nullable: false
            column: entity_id
        entityType:
            type: integer
            unsigned: false
            nullable: false
            column: entity_type
    manyToOne:
        city:
            targetEntity: City
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
