zeba:
  prefix: /
  resource: "@ZEBABundle/Resources/config/routing.yml"
fos_user_change_password:
  prefix: /profile
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
fos_user_profile:
  prefix: /profile
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
fos_user_register:
  prefix: /register
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
fos_user_resetting:
  prefix: /resetting
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
github_login:
  pattern: /login/check-github

location:
  path: /location
  defaults:  { _controller: ZEBABundle:Location:index }
geocode:
  path: /geocode
  defaults:  { _controller: ZEBABundle:Location:geocode}
homepage:
  pattern: /
gettoken:
  path: /api/getToken

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


homeitems:
  type: rest
  resource: ZE\BABundle\Controller\HomeItemsController
  prefix:   /api

genres:
  type: rest
  resource: ZE\BABundle\Controller\GenresController
  prefix:   /api


bands:
  type: rest
  resource: ZE\BABundle\Controller\BandsController
  prefix:   /api

userbands:
  type: rest
  resource: ZE\BABundle\Controller\UserBandsController
  prefix:   /api