NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

bandaid_demo_securityrest:
    resource: Bandaid\BandaidUserBundle\Controller\SecurityController
    type: rest

bandaid_demo_userrest:
    resource: "@BandaidBandaidUserBundle/Resources/config/userrest_routes.yml"
    type: rest
    prefix: /api