zeba:
  prefix: /
  resource: "@ZEBABundle/Resources/config/routing.yml"
gettoken:
  path: /api/open/getToken

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


homeitems:
  type: rest
  resource: ZE\BABundle\Controller\HomeItemsController
  prefix:   /api/open

genres:
  type: rest
  resource: ZE\BABundle\Controller\GenresController
  prefix:   /api


bands:
  type: rest
  resource: ZE\BABundle\Controller\BandsController
  prefix:   /api/open

userbands:
  type: rest
  resource: ZE\BABundle\Controller\UserBandsController
  prefix:   /api/secure
useritems:
  type: rest
  resource: ZE\BABundle\Controller\UserItemsController
  prefix:   /api/secure
