security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH,ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        gettoken:
            pattern:  ^/api/getToken$
            stateless: true
            gfreeau_get_jwt:
                # this is the default config
                username_parameter: username
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: ze_user_security.authentication.handler.login_failure_handler

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    github:             "/login/check-github"
                    twitter:             "/login/check-twitter"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: zeba_user_provider
            anonymous:    true
            logout:
                path: fos_user_security_logout
                success_handler: ze_user_security.authentication.handler.logout_success_handler
            switch_user: true

        api:
            pattern:    ^/api
            stateless:  true
            lexik_jwt: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN,ROLE_SUPER_ADMIN] }
        - { path: ^/api/homeitems$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/genres$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/bands$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/*, roles: [ IS_AUTHENTICATED_FULLY ] }