

ZEBABundle_document:
  resource: "@ZEBABundle/Resources/config/routing/document.yml"
  prefix:   /document
ZEBABundle_band:
  resource: "@ZEBABundle/Resources/config/routing/band.yml"
  prefix:   /band
ZEBABundle_musician:
  resource: "@ZEBABundle/Resources/config/routing/musician.yml"
  prefix:   /musician
ZEBABundle_user:
  resource: "@ZEBABundle/Resources/config/routing/user.yml"
  prefix:   /user      
ZEBABundle_message:
  resource: "@ZEBABundle/Resources/config/routing/message.yml"
  prefix:   /message
ZEBABundle_api:
  resource: "@ZEBABundle/Resources/config/routing/api.yml"
  prefix:   /api