parameters:
    my_user_provider.class: ZE\BABundle\Service\Security\FOSUBUserProvider
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, github: githubID}]

    menu.voter.request:
        class: ZE\BABundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
    sonata.user.admin.group:
        abstract: true
        public: false
    geocoder.listener:
        class:  ZE\BABundle\Doctrine\Listener\GeocoderEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    security.access.post_voter:
        class:      ZE\BABundle\Security\Authorization\Voter\AssociationVoter
        public:     false
        tags:
            - { name: security.voter }
    zeba.twig.file.exists.extension:
        class: ZE\BABundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension" }