parameters:
    zeba_user_provider.class: ZE\BABundle\Service\Security\FOSUBUserProvider
    ze_user_security.authentication.handler.login_success_handler.class: ZE\BABundle\Security\Authentication\Handler\LoginSuccessHandler
    ze_user_security.authentication.handler.logout_success_handler.class: ZE\BABundle\Security\Authentication\Handler\LogoutSuccessHandler
    ze_user_security.authentication.handler.login_failure_handler.class: ZE\BABundle\Security\Authentication\Handler\LoginFailureHandler
services:
    zeba_user_provider:
        class: "%zeba_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, github: githubID}]

    menu.voter.request:
        class: ZE\BABundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

    sonata.user.admin.group:
        abstract: true
        public: false
    geocoder.listener:
        class:  ZE\BABundle\Doctrine\Listener\GeocoderEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    security.access.post_voter:
        class:      ZE\BABundle\Security\Authorization\Voter\AssociationVoter
        public:     false
        tags:
            - { name: security.voter }
    zeba.twig.file.exists.extension:
        class: ZE\BABundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension" }

    zeba.listener.JoinBandRequestEvent:
        class: ZE\BABundle\EventListener\JoinBandRequestEventListener
        arguments:
            ['@service_container']
        tags:
            - { name: kernel.event_listener, event: zeba.band.join_request, method: onJoinBandRequestEvent }
    zeba.listener.JoinBandAcceptEvent:
        class: ZE\BABundle\EventListener\JoinBandAcceptEventListener
        arguments:
            ['@service_container']
        tags:
            - { name: kernel.event_listener, event: zeba.band.join_accept, method: onJoinBandAcceptEvent }
    ze_user_security.authentication.handler.login_success_handler:
        class:  %ze_user_security.authentication.handler.login_success_handler.class%
        arguments:  ['@service_container']
        calls:
            - [setSession, ["@session"]]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    ze_user_security.authentication.handler.logout_success_handler:
        class:  %ze_user_security.authentication.handler.logout_success_handler.class%
        arguments:  [@router]

        tags:
            - { name: 'monolog.logger', channel: 'security' }
    ze_user_security.authentication.handler.login_failure_handler:
        class:  %ze_user_security.authentication.handler.login_failure_handler.class%
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    ze.event_listener_set_url:
        class:  ZE\BABundle\EventListener\SetUrlEventListener
        arguments:  [@router]
        calls:
            - [setSession, ["@session"]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
