bandaid_bandaid_user_homepage:
    pattern:  /
    defaults: { _controller: BandaidBandaidUserBundle:Default:index }


# src/Ens/JobeetBundle/Resources/config/routing.yml
BandaidBandaidUserBundle_entity:
    resource: "@BandaidBandaidUserBundle/Resources/config/routing/entity.yml"
    prefix: /entity

