EntityGenre:
    type: entity
    table: entity_genre
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        genre:
            targetEntity: Genre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                genre_id:
                    referencedColumnName: id
            orphanRemoval: false
        entity:
            targetEntity: Entity
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                entity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
