Media:
    type: entity
    table: media
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        filename:
            type: integer
            unsigned: false
            nullable: false
        extension:
            type: string
            length: 3
            fixed: true
            nullable: true
        isPublic:
            type: boolean
            nullable: true
            column: is_public
    manyToOne:
        type:
            targetEntity: MediaType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
