MediaType:
    type: entity
    table: media_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: 32
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
